In [1]:
import numpy as np
import nashpy as nash

In [2]:
n_max = 40
A = n_max - np.array([[n_max, 5, 5],
              [10, 10, 10],
              [20, 20, 20]])
B = n_max - np.array([[n_max, 20, 30],
              [10, 20, 30],
              [10, 20, 30]])
juego = nash.Game(A, B)
eqs = np.array(list(juego.support_enumeration()))

print("A:\n", A)
print("B:\n", B)
print("Eqs:\n",eqs)

A:
 [[ 0 35 35]
 [30 30 30]
 [20 20 20]]
B:
 [[ 0 20 10]
 [30 20 10]
 [30 20 10]]
Eqs:
 [[[1.         0.         0.        ]
  [0.         1.         0.        ]]

 [[0.         1.         0.        ]
  [1.         0.         0.        ]]

 [[0.33333333 0.66666667 0.        ]
  [0.14285714 0.85714286 0.        ]]]


In [3]:
for i in range(eqs.shape[0]):
    sigma_r = eqs[i][0]
    sigma_c = eqs[i][1]
    sigmas = juego[sigma_r, sigma_c]
    print("Estrategia {}: Sigmas: {}.".format(i,sigmas))

Estrategia 0: Sigmas: [35. 20.].
Estrategia 1: Sigmas: [30. 30.].
Estrategia 2: Sigmas: [30. 20.].
