In [1]:
import numpy as np
import nashpy as nash

In [2]:
A = np.array([[0, 20],
              [10, 10]])
B = np.array([[0, 5],
              [10, 5]])

juego = nash.Game(A, B)
eqs = np.array(list(juego.support_enumeration()))

print("A:\n", A)
print("B:\n", B)
print("Eqs:\n",eqs)

A:
 [[ 0 20]
 [10 10]]
B:
 [[ 0  5]
 [10  5]]
Eqs:
 [[[1.  0. ]
  [0.  1. ]]

 [[0.  1. ]
  [1.  0. ]]

 [[0.5 0.5]
  [0.5 0.5]]]


In [3]:
best = 0
i_best = 0
for i in range(eqs.shape[0]):
    sigma_r = eqs[i][0]
    sigma_c = eqs[i][1]
    sigmas = juego[sigma_r, sigma_c]
    print("Estrategia {}: Sigmas: {}.".format(i,sigmas))
    if (sigmas[0] + sigmas[1])>(best):
        best = sigmas[0] + sigmas[1]
        i_best = i
        

Estrategia 0: Sigmas: [20.  5.].
Estrategia 1: Sigmas: [10. 10.].
Estrategia 2: Sigmas: [10.  5.].


In [4]:
print("La mejor estrategia es la número {}. El payoff máximo es {}.".format(i_best, best))
ruta_1 = np.where(np.array(eqs[i_best][0]) == 1)[0][0]
ruta_2 = np.where(np.array(eqs[i_best][1]) == 1)[0][0]
print("Jugador: 1. Ruta: {}.".format(ruta_1))
print("Jugador: 2. Ruta: {}.".format(ruta_2))

La mejor estrategia es la número 0. El payoff máximo es 25.0.
Jugador: 1. Ruta: 0.
Jugador: 2. Ruta: 1.
